adding jstack and node also removing maven settings url - trying to pull from environment - will deploy now

diff --git a/bin/compile b/bin/compile
--- a/bin/compile
+++ b/bin/compile
@@ -12,6 +12,42 @@ BUILD_DIR=$1
 CACHE_DIR=$2
 LOGGER_FLAGS=""
 
+bp_dir=$(cd $(dirname $0); cd ..; pwd)
+
+# Load some convenience functions like status(), echo(), and indent()
+source $bp_dir/bin/common.sh
+
+# Output npm debug info on error
+trap cat_npm_debug_log ERR
+
+# Resolve node version using semver.io
+node_version="0.10.31"
+
+# Download node from Heroku's S3 mirror of nodejs.org/dist
+status "Downloading and installing node"
+node_url="http://s3pository.heroku.com/node/v$node_version/node-v$node_version-linux-x64.tar.gz"
+curl $node_url -s -o - | tar xzf - -C $BUILD_DIR
+
+mkdir -p $BUILD_DIR/.startup
+cat << EOF > $BUILD_DIR/.startup/java_with_jstack
+  javacmd="java \$@"
+  eval "\$javacmd &"
+  pid=\$!
+
+  while :
+  do
+    sleep 180
+    kill -3 \$pid
+  done
+EOF
+chmod +x $BUILD_DIR/.startup/java_with_jstack
+
+# Move node (and npm) into ./vendor and make them executable
+mkdir -p $BUILD_DIR/vendor
+mv $BUILD_DIR/node-v$node_version-linux-x64 $BUILD_DIR/vendor/node
+chmod +x $BUILD_DIR/vendor/node/bin/*
+PATH=$BUILD_DIR/vendor/node/bin:$PATH
+
 curl --silent --location http://heroku-jvm-common.s3.amazonaws.com/jvm-buildpack-common.tar.gz | tar xz
 . bin/java
 
@@ -82,7 +118,6 @@ if [ ! -d .maven ]; then
   echo " done"
 fi
 
-MAVEN_SETTINGS_URL="https://raw.githubusercontent.com/amstatz/amstatz-replica-buildpack/master/opt/settings.xml"
 if [ -f .m2/settings.xml ]; then
   rm .m2/settings.xml 
 fi
